management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

feign:
  hystrix:
    enabled: true

services:
  # This property is only used when running locally.
  backend: http://localhost:8081
